{% set name = "xtensor-blas" %}
{% set version = "0.17.1" %}
{% set sha256 = "87a66984321d9ed245cfc9aff91e409492069c704675f995efb5e7f6fde24d06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor-blas/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - xtensor >=0.21.2,<0.22.0
  run:
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/include/xtensor-blas/xblas.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-blas\xblas.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blasConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blasConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'BLAS extension to xtensor'
  description: 'xtensor-blas is an extension to the xtensor library, offering bindings to BLAS and LAPACK libraries through cxxblas and cxxlapack from the FLENS project.'
  doc_url: http://xtensor-blas.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-blas

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
